repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-symlinks
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: double-quote-string-fixer
      # - id: end-of-file-fixer
      - id: forbid-new-submodules
      # - id: mixed-line-ending
      # - id: trailing-whitespace
      # - id: pretty-format-json
        args: ["--autofix"]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.0
    hooks:
      - id: gitleaks
